'use strict';
const fs = require('node:fs');
const path = require('node:path');
const core = fs.readFileSync(path.join(__dirname, 'src/core.js'), 'utf8');
const opencode = fs.readFileSync(path.join(__dirname, 'src/opencode.js'), 'utf8');
const main = fs.readFileSync(path.join(__dirname, 'src/main.js'), 'utf8');
const bundled = main.replace("require('./core')", '__codexReaderCore').replace("require('./opencode')", '__codexReaderOpenCode');
if (bundled === main) throw new Error('Core import not found');
fs.writeFileSync(path.join(__dirname, 'main.js'), '// Generated by node build.js. Edit src/ files.\n' +
  'const __codexReaderOpenCode = (() => { const module = { exports: {} };\n' + opencode + '\nreturn module.exports; })();\n' +
  'const __codexReaderCore = (() => { const module = { exports: {} };\n' + core + '\nreturn module.exports; })();\n' + bundled);
console.log('Built main.js (no runtime dependencies except Obsidian and Node)');
